### PR TITLE
German language added

### PR DESCRIPTION
**Pull request by vanieka-sharma**

### CODE REVIEW

**Review by chirag-jn — CHANGES_REQUESTED** [review]
Please follow the steps specified in `LANGUAGES.md` for adding a new language. Multiple changes are required in this PR.

**Comment by chirag-jn** [comment]
I have left some comments. Please check the same. Also shouldn't it be de instead of gem in values folder name and string variables?
Ref: https://stackoverflow.com/questions/7973023/what-is-the-list-of-supported-languages-locales-on-android

**Comment by chirag-jn** [comment]
Please rebase and fix merge conflicts too.

**Comment by chirag-jn** [comment]
Please add copyright to `values-de/strings.xml`. Refer `values/strings.xml` for the format and text.

**Comment by vanieka-sharma** [comment]
I had  already added copyright, and when I forked the repo there was no
tamil file so how should I resolve the merge conflict?

**Pull request merged**
