### PR TITLE
Update Action Bar title with audio change

### PR DESCRIPTION
**Pull request by adi23arora**
This fixes https://github.com/amahi/android/issues/329.

### CODE REVIEW

**Comment by octacode** [comment]
has been already fixed by #69

**Comment by cpg** [comment]
I went with #331 by @ArihantJain456 because that change was larger (had additional things in it). I realized it would conflict with this.

Looking at the conflict, there is a possible slight difference in logic (near as I can tell, without knowing the APIs in detail).

Could you and @ArihantJain456 try and see of resolving the issues here and either fix the conflict or close it?

**Comment by ArihantJain456** [comment]
@adi23arora App is working fine and also title is changing on changing audio.
Please check the latest beta branch and verify it. And if you think there is something wrong with the titles then  we will resolve it, otherwise close the PR.

**Comment by adi23arora** [comment]
Ok, I guess @ArihantJain456  have already solved it [here](https://github.com/amahi/android/blob/e832b0eab3abc21095936edd1be69fd78a407b7a/src/main/java/org/amahi/anywhere/activity/ServerFileAudioActivity.java#L199-L205) with a different approach (using a Parcelable array) for storing the audio file meta data used for displaying audio related info.

I will close this PR.

**Pull request closed without merging**
