### PR TITLE
Fix keyboard covering up login fields

### PR DESCRIPTION
**Pull request by joydeepsaha05**
Fix issue #21

### CODE REVIEW

**Comment by joydeepsaha05** [comment]
@cpg Please could you test this out? I could see the sign in button along with the other fields on my devices.

**Comment by hshrimali** [comment]
@joydeepsaha05 Sorry to say, but I am already working on this issue for so long and also sent the PR few days back and many PRs earlier also.

**Comment by joydeepsaha05** [comment]
@hshrimali I had noticed your closed pull requests but failed to see the open one. Looked at your code and it seems to be a over-complicated fix.

**Comment by cpg** [comment]
Well, this seems to work pretty well and it's a one-line change. Why did anyone not think of this?

PS: @hshrimali, having done a bunch of work is no reason to discard a good solution.

**Comment by hshrimali** [comment]
Look at the screenshot of the changes that @joydeepsaha05 did to remove this issue. It still hides the SignIn button in my device. And @cpg, I tried to remove this issue with the same thinking in my first  PR #50 . At that time , you were the only one who suggested me to use some sensible things done in mainstream apps like Skype (they move the logo and the fields up top of the screen), Facebook Messenger (they slide the whole page up to the point the logo is not visible any more) and many more. That's why I started working in that direction. If still you want to go with @joydeepsaha05 solution, then okay I will close my PR for this issue. And @cpg Sorry for not thinking like @joydeepsaha05 solution and going for some sensible things. From now onwards, I would try my level best to provide you with a good solution instead of some bunch of work.

screenshot_20170331-094222

**Pull request merged**
