### PR TITLE
Feature: Sort files by descending order of size

### LINKED ISSUE #441: Sort files by descending order of size
**Describe the issue**
Some times user wants to know which files have more size and viceversa. So letting the user sort according to descending order of file size will be really helpful.

I am going to work on this.

### PR DESCRIPTION
**Pull request by balaji-ramavathu**
Fixes #441 

**Screenshots**

sort-size

**Summary of the changes made**

Added sort_size icon and the flow of icons goes like this : sort_name - > sort_modification_time - > sort_size - > sort_name 
A comparator class is added to ServerFilesFragment to compare sizes of files in the list and sort them in descending order.

### CODE REVIEW

**Review by csoni111 — COMMENTED** [review]
See if you find a single vector image for the size sort icon instead of the png @balaji-ramavathu. Rest everything looks fine.

**Comment by adi23arora** [comment]
When we have more than 2 sorting options, shouldn't that be displayed in a list from where the user can select the sorting option he wants, instead of switching it by continuously clicking on a single button?

**Comment by balaji-ramavathu** [comment]
@adi23arora I think we need to do that when there are more than 3 sorting options. And I think there's no need to add any more sorting ways in the future.These three options are enough. What do you say? @csoni111 ?

**Comment by csoni111** [comment]
Well there can be more than 3 options. Currently all options are sorting in descending order, we may want to include ascending orders too in future but for now I guess this is fine, we can look for the UI to display all sorting options later on.

**Comment by balaji-ramavathu** [comment]
@csoni111 Yeah I agree. Also, I'm not able to find vector image for the same icon. But I found a similar one which looks like this. Can you tell me if this is okay ?
sort-descending
(Click above to see the image. Won't be visible here since the icon is white :-P )

**Comment by csoni111** [comment]
Yes that is fine. You can try this too, its almost similar to the original one. 
https://visualpharm.com/assets/950/Descending%20Sorting-595b40b85ba036ed117dc061.svg

**Comment by balaji-ramavathu** [comment]
@csoni111 thanks :) I have used your link and changed it to vector drawable.

**Pull request merged**
