### PR TITLE
ImageView is overlapping over TextView

### LINKED ISSUE #412: TextView overlapping ImageView in RelativeLayout
When text is long, it overlaps the more_options ImageView on its right, covering it as shown in figure below.

screenshot_2019-02-16-17-30-33-155_org amahi anywhere

After solving, it will look like this-

screenshot_2019-02-16-18-17-28-397_org amahi anywhere

### PR DESCRIPTION
**Pull request by shivammaindola**
Fixes #412

### CODE REVIEW

**Comment by shivammaindola** [comment]
@octacode @cpg Can you please review this PR?

**Comment by cpg** [comment]
I wonder ... how does it behave when the screen is rotated?

The code changes are very small, so it looks ok if it works well.

**Comment by shivammaindola** [comment]
It just look like this when the screen is rotated.

screenshot_2019-02-19-07-02-51-736_org amahi anywhere

@cpg Code is working fine in portrait and landscape too.

**Comment by shivammaindola** [comment]
@cpg  @octacode can you please merge it?

**Pull request merged**
