### PR TITLE
Empty state when there is nothing to show on the Home Page

### PR DESCRIPTION
**Pull request by Sreyas-108**
In reference to issue #411

### CODE REVIEW

**Comment by iadeelzafar** [comment]
@Sreyas-108 whenever you're making a PR that has some UI changes. Don't forget to add the GIF showing those changes.

**Comment by octacode** [comment]
Hi @Sreyas-108, it's a rarity that the user will will not have any shares. However, this addition won't do us any harm. There is also a very fair chance that the folders inside the shares are also empty. Are we displaying the empty message there? If not then that would be a good addition.

**Comment by cpg** [comment]
@iadeelzafar maybe you can follow the suggestion?

**Comment by Sreyas-108** [comment]
@cpg I am underway with the suggestion provided by @octacode . Will send a PR soon.

**Comment by Sreyas-108** [comment]
@cpg I am underway with the suggestion provided by @octacode . Will send a PR soon.

**Review by iadeelzafar — CHANGES_REQUESTED** [review]
Could you please squash your commits into a single one?

**Review by iadeelzafar — CHANGES_REQUESTED** [review]
Also, could you please rename the commit message? Here's a useful resource to help you with commit messages. [How to write better commit messages](https://github.com/erlang/otp/wiki/writing-good-commit-messages)
You can do so by amending into your previous commit and then renaming.
Using ```git commit --amend```

**Comment by Sreyas-108** [comment]
I will amend them accordingly. I havent squashed them since all changes havent been committed. Will do it once all changes are complete.

**Comment by chirag-jn** [comment]
In accordance with #449, we are now showing shares on the home page. So we don't have to show an empty state screen anymore.

**Comment by cpg** [comment]
We don't need this any more because we show shares.

**Pull request closed without merging**
