### PR TITLE
Tell a friend feature improved

### PR DESCRIPTION
**Pull request by doomers**
#92 Now Tell-a-friend Screen looks like this

screenshot_20170317-134544

### CODE REVIEW

**Comment by doomers** [comment]
@cpg Please review this PR, if there is something that needed to be changed.
Thanks.

**Comment by doomers** [comment]
@okay, I will create a String Resource and use it

**Comment by doomers** [comment]
@octacode Done, Please review it now.

**Comment by cpg** [comment]
Conflicts need to be resolved in this PR. Please take a look when you can.

**Comment by doomers** [comment]
@cpg sorry for the delay, working on vector-drawable issue from morning, now please review this.

**Comment by doomers** [comment]
@cpg please review this when you have time.

**Pull request merged**
