### PR TITLE
Add passcode with fingerprint Auth to lock an app

### LINKED ISSUE #453: Add an option to ask for password or pattern everytime application start
To make our application more secure, we can add the privacy feature in settings where a user can set his own password or a pattern to unlock the app during startup. User can disable or enable this feature from the settings at any time.

It will look like this.

lock

### PR DESCRIPTION
**Pull request by shivammaindola**
Fix: #453 
Added Following things-
- Fallback pass code on the fingerprint lock screen. At times your finger may be dirty or just that your fingerprint might not work.
- Sign out button on the lock screen.

**lock screen will look like this-**

Screenshot_2019-04-27-18-19-05-149_org amahi anywhere

You can check a gif [here](https://drive.google.com/drive/u/0/folders/1-0djaHncOJLpadsruGbTWiyPz8AZLUHQ)

### CODE REVIEW

**Comment by shivammaindola** [comment]
@cpg @csoni111 can you please help me to resolve this error?

**Comment by balaji-ramavathu** [comment]
hey @shivammaindola I think the problem occurs while the travis is trying to test the code in the emulator and the app screen is somehow blocked from being displayed either by the lock screen or some 'Welcome' dialog of the emulator. You might see this problem by testing the code in the emulator yourself. So to solve this, try adding this code in the AuthenticationActivityTest :

`@Before
    public void unlockScreen() {
        final AuthenticationActivity activity = authenticationActivityTestRule.getActivity();
        Runnable wakeUpDevice = new Runnable() {
            public void run() {
                activity.getWindow().addFlags(WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON |
                    WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED |
                    WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
            }
        };
        activity.runOnUiThread(wakeUpDevice);
    }`

And test it in the emulator. If that doesn't work, go through this [link](https://github.com/travis-ci/travis-ci/issues/6340) and look for other solutions discussed there.

**Comment by shivammaindola** [comment]
@balaji-ramavathu Thank you for the help, I'll try to solve it.

**Comment by shivammaindola** [comment]
@cpg @csoni111 can you please review this PR?

**Review by Akash-Ramjyothi — COMMENTED** [review]
This PR does not works and shows NullPointerException error on the code. And you must note that not all phones will be having fingerprint sensors, even if they have, it won't be on the screen and it would be at the back. I strongly recommend @cpg to reject this PR and close it.

**Comment by cpg** [comment]
Closing

**Pull request closed without merging**
