### PR TITLE
Pressing effects/feedback (fixes #296)

### LINKED ISSUE #296: Items on share screen doesn't show any pressing effect
Items on below screen like "Demo" doesn't show any pressing effect on pressing.

screenshot_2018-03-01-19-23-12

### PR DESCRIPTION
**Pull request by mohitsvnit**
Modified the code for pressing effect on items of share screen. 

screenshot_2018-03-02-15-47-16

### CODE REVIEW

**Comment by cpg** [comment]
I wonder why there is a commit for "Added introductory screen button in settings. Issue #294". should that not be separate?

**Comment by mohitsvnit** [comment]
Actually It was commit before. I didn't know how to remove that. 
but the content of that commit is already merged by you in my previous PR.

**Comment by octacode** [comment]
[https://stackoverflow.com/questions/927358/how-to-undo-the-most-recent-commits-in-git](https://stackoverflow.com/questions/927358/how-to-undo-the-most-recent-commits-in-git)

@mohitsvnit Please give this a look

**Comment by mohitsvnit** [comment]
I will remove those unnecessary commit

**Comment by cpg** [comment]
Also, looking at the #296 bug, and in my own device, I do see effects. You went from others saying there are effects to you "solving" the issue without explaining. We don't like to push things through just for the sake of it. We prefer to know why we're doing things.

**Comment by mohitsvnit** [comment]
My device: Coolpad Note3 lite
Os: Android 5.1 sdk level=22
I can't see any pressing effect in my device.

**Comment by cpg** [comment]
Did you test in Android 6, 7 or 8? 95+% of our installed base is on those OSs. In fact about 55% are on 7+

**Comment by mohitsvnit** [comment]
ok. I will test them and let you know.

**Comment by cpg** [comment]
Correction, 81+% are on 7+

**Pull request closed without merging**
