### PR TITLE
Add french strings

### PR DESCRIPTION
**Pull request by Eradash**
There is some missing translations, the context was not clear enough for me. I did not build the application, try it to let Android Studio spot them (surely some ' without \ before)

### CODE REVIEW

**Comment by cpg** [comment]
It looks like it failed to build. Did you have a chance to built it yourself?

**Comment by Eradash** [comment]
It looks like the failed build is not due to my modifications...
image
I tried on my computer, and it's the same result for my branch, and the `beta` branch.
Even when updating all tools and dependencies, the project would not build... From what I know, the recyclerview-v7 is included multiple times in dependencies, and must be excluded to keep only one

**Comment by cpg** [comment]
@ArihantJain456 that being the case, it's really up to us to remove that, not up to him providing an unrelated PR, really. No?

**Comment by Eradash** [comment]
Even after removing the dependency, there is still the same error appearing on my side

**Comment by ArihantJain456** [comment]
@Eradash the error is still occuring since it is trying to download recyclerview from bintray first instead of maven, which I have taken care in the PR #391.

**Comment by ArihantJain456** [comment]
@cpg can you rerun the Travis build?

**Comment by cpg** [comment]
It passed, though I did notice this:

```
warning: string 'application_name' marked untranslatable but exists in locale 'fr'
```

**Comment by cpg** [comment]
does the warning mean that there are other things that need to be done in the code to enable the `fr` strings? or is adding the strings file for `fr` enough?

is it automatic based on the user's language in the OS or does it require user selection or override?

**Comment by Eradash** [comment]
The warning appears because the string is present in the french ones, even if the line was marked as not translatable. I simply forgot to remove the line...

Only adding the file named exactly as the english one is enough. It is placed in a directory tagged `-fr` to indicate the OS to look for this file first if the locale is set to french. It is automatic.

**Comment by cpg** [comment]
Thanks for the explanation. Are you saying there is one extra line that needs to be removed now?

**Comment by Eradash** [comment]
`<string name="application_name" translatable="false">Amahi</string>`
This line in the French file is not necessary since it's defined as non translatable in the main file. I did not check the tags, only the values...

**Pull request merged**
