### PR TITLE
adds show password functionality addressed in issue #19

### PR DESCRIPTION
**Pull request by mehtamanan0**
amahiswa

### CODE REVIEW

**Comment by csoni111** [comment]
Just a suggestion: Following the material design guidelines, instead of a checkbox, `TextInputEditText` and `TextInputLayout` can be used given in the latest android support design library to solve issue #19. It supports password toggle feature by default.

Reference: [Material Guidelines](https://material.io/guidelines/components/text-fields.html#text-fields-password-input)

**Comment by mehtamanan0** [comment]
hmm nice suggestion @csoni111  will do that!

**Comment by cpg** [comment]
If I may, my main concern with this view, usability wise, is how the keyboard popping up covers all or most of the input fields. This happens with regular phones vertically.

 The logo should be either higher, smaller  (or both) or even under the whole set of input fields and the sign in button altogether. This way the keyboard would block the logo (and not the input fields) saving the user some awkward interactions to move field to field.

**Comment by mehtamanan0** [comment]
For this issue we can address it either by using WindowSoftInputmode 
Refer here: https://android-developers.googleblog.com/2009/04/updating-applications-for-on-screen.html 

Or the other  option is to Change the complete layout itself.
@cpg what would you prefer?

**Comment by top-gun007** [comment]
@mehtamanan0 I reported the issue first and it wasn't even approved so how come you went on to sending the PR I was planning on doing it.

**Comment by top-gun007** [comment]
@cpg can you look into it please.

**Comment by mehtamanan0** [comment]
@top-gun007 Sorry for that i will remove my PR.

**Pull request closed without merging**
