### PR TITLE
Added RTL (Right to Left) support.

### LINKED ISSUE #700: Missing RTL Support
**Describe the issue**
At many places, RTL support is not functioning properly or is completely missing. There should be consistent RTL support all across the app. (Screenshots attached below)

**Steps to reproduce behavior**
Turn on RTL mode on an android device by enabling Force RTL layout direction in developer options. After that, please look at the screenshots that I am attaching of the current behavior of the app.

**Current behavior**

1. Look at the layout of the card view item ( Ex. Demo folder ) it is not working properly for RTL.

image

2. Alignment of Server selection is not correct

image

3. Direction of the up arrow in settings is not correct.

image

4. No RTL support in file sort bottom sheet.

image

5. Upload heading misaligned. 

image

6. Songs item layout is not working properly for RTL.

image

**Expected behavior**

image

image

image

image

image

image

**Smartphone (please complete as much of the following information as possible):**
 All devices with RTL mode turned on.

**Additional context**
Since we are adding Localization support it will be better if we fix this issue first hand.

### PR DESCRIPTION
**Pull request by Prakhar-Agarwal-byte**
@cpg @chirag-jn I have added RTL support for the app addressing the issue (#700  ).

- [x] Fixes #700 

Screenshots showing that the PR is working correctly.

image

image

image

image

image

image

### CODE REVIEW

**Comment by chirag-jn** [comment]
RTL is always tricky and using English language for testing that might not be appropriate. We aren't yet sure if the UI is robust enough to handle RTL. Enough verification is required. Will get back to this soon.

**Comment by cpg** [comment]
This looks (from my superficial review) relatively low risk, considering RTL could be a great feature for some languages.

Questions:
* how does RTL get selected? (phone settings, per-app settings?)
* who selects it? (does the user actively turn it on?)
* how would a new RTL locale would select RTL by default? (could it be overridden by the user?)

**Comment by Prakhar-Agarwal-byte** [comment]
@cpg 
1) RTL gets selected when the user selects a language, in the app, that is written RTL.
2) Yes, same as above, user selects it 
3) When the user selects a language, it triggers this function
    `private void setUpLanguage() {
        LocaleHelper.setLocale(getContext(), getLanguage());
        tearDownActivity();
    }`

     which, in turn, calls

```
`private static Context updateResources(Context context, String language) {
        Locale locale = new Locale(language);
        Locale.setDefault(locale);

        Configuration configuration = context.getResources().getConfiguration();
        configuration.setLocale(locale);
        configuration.setLayoutDirection(locale);

        return context.createConfigurationContext(configuration);
    }`
```
`configuration.setLayoutDirection(locale);`
this line deduces the layout direction based on the selected language and applies it

**Comment by cpg** [comment]
Thanks. So it's really embedded in the locale. I do not think we have any RTL locales as of yet, no?

Could you take a look at the conflicts? (no rush)

**Comment by Prakhar-Agarwal-byte** [comment]
@cpg 
Yes, currently we don't have any RTL Locales. I'm fixing the conflicts now.

**Comment by chirag-jn** [comment]
Please rebase and fix conflicts @Prakhar-Agarwal-byte

**Comment by Prakhar-Agarwal-byte** [comment]
@cpg  @chirag-jn 
I have resolved all conflicts and it's working properly

**Comment by chirag-jn** [comment]
@cpg I haven't interacted with RTL apps before and I am not sure how are they supposed to look.

**Pull request merged**
