### PR TITLE
Leading and trailing white-spaces of username will be trimmed before it goes for authentication

### PR DESCRIPTION
**Pull request by mitrukahitesh**

### CODE REVIEW

**Comment by chirag-jn** [comment]
Fixes #525

**Comment by chirag-jn** [comment]
@cpg should we trim the username before it goes for authentication?

**Comment by chirag-jn** [comment]
Or should we let the server handle that?

**Comment by mitrukahitesh** [comment]
With the commit "Space as first character in username will be avoided", user will not be able to enter a space as first character for username. Clicking space will not move the cursor forward if the username field is empty.

**Comment by chirag-jn** [comment]
@mitrukahitesh You have made changes to the master branch. However, all development is happening on the `beta` branch, and I would recommend you to close this PR, make the same changes on the beta branch and create a new PR.

**Comment by mitrukahitesh** [comment]
@chirag-jn Sure. I will do the same. Thank you.

**Pull request closed without merging**
