### PR TITLE
fix change between light and dark them settings app crash

### PR DESCRIPTION
**Pull request by Ahmed-Abd-Elsamie**
@chirag-jn  I have figured out the problem and fixed it.
the problem was in the NavigationActivity.class , after changing between light and dark theme we finish the activity then start it again from itself. and this will cause the app to crash because we are trying to start it from null context.

Solution :
i removed startActivityForResult function and replaced it with the following:
1 - once opening the settings page i finish the navigationActivity.
2 - once do any change in the settings like changing between light and dark themes, we start the NavigationActivity again from the settingActivity.

I tried this method and solved the problem

here is the updated

### CODE REVIEW

**Comment by chirag-jn** [comment]
@Ahmed199810 Please make a fork of the latest `beta` branch since there a lot of conflicts in the files, and there have been enough changes in the codebase in the last few days.

**Comment by chirag-jn** [comment]
Also, please add the code relevant to this PR only. I can see that you have changes present related to NAU and friending activity but those aren't relevant to this PR.

**Comment by chirag-jn** [comment]
Also, if I'm not wrong, this change has been already incorporated in the `beta` branch, please confirm the same.

**Comment by cpg** [comment]
Already in the codebase. Thanks much for your contribution.

**Pull request closed without merging**
