### PR TITLE
Added a new Preference Tell a friend.

### PR DESCRIPTION
**Pull request by octacode**
I have added a new Preference of tell a friend. This launches a shared Intent with the message "Amahi for your android. Download it from here " + playstore link.

screenshot_20170306-140351

OnPreferenceClick Listener :
screenshot_20170306-140358

### CODE REVIEW

**Comment by cpg** [comment]
cool!

what does this do. exactly what message does it send to the friend?

can you post the details of an email or whatever the other person (the new one) sees?

**Comment by octacode** [comment]
@cpg on clicking it. A shared intent will open up giving the playstore link of the app. Here'a snippet of the new Gmail message that will be composed.
screenshot_20170306-182647

**Comment by cpg** [comment]
The only problem is that to be able to use the app one needs to have an Amahi HDA, so installing the app without and HDA will only lead to frustration and possibly bad reviews.

I think the Subject field **has** to be populated, and the message has to be different. These are my suggestions

Subject: Check out my Amahi home server

Message: I use the Amahi home server for storing, backing up and streaming all my files. Check it out! https://www.amahi.org

**Comment by octacode** [comment]
@cpg will update the message.

**Comment by octacode** [comment]
**I have made the changes to the message.**
@cpg Please have a look.
screenshot_20170307-120352

**Comment by octacode** [comment]
Thanks for the merge.

**Pull request merged**
