### PR TITLE
Move Crashlytics keys into a different file

### PR DESCRIPTION
**Pull request by zaclimon**
This seems enough but there is one issue I'm not quite sure how to tackle yet.

It seems that there is only one apiKey used at this time but there are two flavors. Is the same apiKey used for both flavors? (Beta and Release)

### CODE REVIEW

**Comment by cpg** [comment]
Can you clarify what is the status of this PR?

We probably should keep the actual API key in private, like other files.

**Comment by zaclimon** [comment]
The API key was stored in a separate metadata in AndroidManifest.xml. As suggested by Fabric, it is recommended that if Git is used to create a separate fabric.properties and then put the required keys there.

Then the user could keep it's key private by adding the file to his/her .gitignore.

Source:

https://docs.fabric.io/android/fabric/settings/working-in-teams.html#android-projects

Do you have some sort of special private file where you do keep all your API keys?

**Comment by cpg** [comment]
I guess we could use the same api.properties, with different entries for the Crashlytics stuff.

Maybe that is best. Can you change this PR for that?

**Comment by zaclimon** [comment]
Normally the library either checks the API key in the AndroidManifest.xml or fabric.properties. I guess it should be possible for Gradle to build dynamically a fabric.properties based on the contents of api.properties.

I'll take a look at this.

**Comment by cpg** [comment]
Stale

**Pull request closed without merging**
