### PR TITLE
#730 Issue solved

### LINKED ISSUE #730: Adding Press Back Button Again To Exit App Functionality
**Describe the issue**
Currently, the user exits the app as soon as he presses the back button while on Navigation Activity. Since the app requires the user to press the back button to navigate up, the user can often, by mistake, exit the app. To prevent this from happening we should add a toast message that asks the user to press the back button again to confirm that the user surely wants to exit the app.

**To Reproduce or Feature details**
1. Press the back button while on Navigation Activity.
2. Notice that we exit the app without confirmation.

**Current behavior**

App exits without toast message with a single press of the back button

https://user-images.githubusercontent.com/17739006/105395662-fe5d7000-5c44-11eb-95ca-2735cb5e15dc.mp4

**Expected behavior**

Toast message shows up asking the user to press the back button again. If the user presses the button again in a certain time limit, only then the app exit.

https://user-images.githubusercontent.com/17739006/105395320-9b6bd900-5c44-11eb-9b44-87f5cef04ea0.mp4

**Smartphone (please complete as much of the following information as possible):**
 - Should run on all supported Android devices.

### PR DESCRIPTION
**Pull request by masterishaan19**
This edit solves issue #730. A toast message will be displayed again for asking the user to press the back button again for exiting the application.

### CODE REVIEW

**Comment by Prakhar-Agarwal-byte** [comment]
@masterishaan19 I have already created a PR for the same issue earlier. #731

**Comment by masterishaan19** [comment]
As It was not yet marked checked / resolved so tried solving it in my way.

**Comment by Prakhar-Agarwal-byte** [comment]
@masterishaan19 I think first we should see if someone has already done/doing work on an issue and then start working on it or you can also ask if you want to start working on an issue. So that any confusion is avoided.

**Comment by chirag-jn** [comment]
Fixed in #731. Not sure about how to proceed here @cpg

**Comment by cpg** [comment]
Thanks @ masterishaan19 for your contribution!

Seeing how #731 has a complete set of locales, etc., we will go with that one. Thanks again!

**Pull request closed without merging**
