### PR TITLE
Displays a message when the field is empty and when user clicks on the Sign In Action Button.

### PR DESCRIPTION
**Pull request by octacode**
screenshot_20170306-160555

### CODE REVIEW

**Comment by mehtamanan0** [comment]
@octacode Nice! I would like to give a suggestion , try to chenge the edittext colors to red while displaying this message.

**Comment by octacode** [comment]
@mehtamanan0 Nice suggestion. Will do

**Comment by octacode** [comment]
@cpg @mehtamanan0 
Hey! I have made the changes. Please have a look at the screen shots.
*If both fields are empty*
screenshot_20170306-195545
*if either of the field is empty*
screenshot_20170306-195555

**Comment by mehtamanan0** [comment]
@octacode Looks good!

**Comment by pulkit4tech** [comment]
@octacode you can also try calling setError("Some Error msg") on EditText some like this [here](http://stackoverflow.com/questions/18225365/show-error-on-the-tip-of-the-edit-text-android)

**Comment by octacode** [comment]
@pulkit4tech, I already am displaying an error message below like the other authentication error messages. :)

**Comment by octacode** [comment]
@cpg can you please give this a look. :)
Thanks

**Pull request merged**
