### PR TITLE
should be using handler in splash screen

### PR DESCRIPTION
**Pull request by prince-09**
The splash screen should be using a handler for a better experience.

### CODE REVIEW

**Comment by prince-09** [comment]
@cpg  please review.

**Comment by chirag-jn** [comment]
There is no need to add a handler in the splash activity. It changes as soon as the next activity starts. So the timing is dynamic.

**Review by chirag-jn — COMMENTED** [review]
The delay isn't necessary.

**Comment by cpg** [comment]
Closing based on recommendation, as the next activity takes care of it.

**Pull request closed without merging**
