### PR TITLE
Create ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md

### LINKED ISSUE #401: Missing Issue Template
This repository is missing an issue template. Issue template allows the contributor to express their  issues in a much better way.

### LINKED ISSUE #406: Missing Pull request template
This repository does not contain Pull request template. If we add PR template it would be better for developers while pushing the changes and making a Pull request.

### PR DESCRIPTION
**Pull request by RajaVamsi11**
**Summary**
Fixes #401 
Fixes #406 
Created an issue template file and pull request template file so that developers find easy while creating an issue and while making pull requests.
You can take a look at those templates. [Issue Template](https://github.com/RajaVamsi11/android/blob/beta/ISSUE_TEMPLATE.md). [Pull request Template](https://github.com/RajaVamsi11/android/blob/beta/PULL_REQUEST_TEMPLATE.md)

### CODE REVIEW

**Comment by RajaVamsi11** [comment]
@octacode @cpg Can you please review this PR?

**Comment by cpg** [comment]
Used your template towards the GH feature in templates. Thanks!

**Comment by RajaVamsi11** [comment]
It's my pleasure. I just wanted to know that Amahi is participating in GSoC this year or not. I am interested in contributing for Amahi for GSoc this year.

**Comment by cpg** [comment]
@RajaVamsi11 it would appear that you may need to peruse our GSoC ideas page, specifically the early section on [what NOT to do](https://wiki.amahi.org/index.php/Google_Summer_of_Code_Ideas#What_to_do_.28and_NOT_do.29_first)

**Comment by RajaVamsi11** [comment]
Sorry for those comments

**Pull request closed without merging**
