### PR TITLE
Feat: Display of last opened of each file

### LINKED ISSUE #488: Display of last opened of each file
**About the issue**
option to store the time and date everytime a file is opened and can be displayed as a part of file info.

### PR DESCRIPTION
**Pull request by balaji-ramavathu**
Fixes #488 

**Changes made**
a new database table to store the last opened of each file
migrated room database version from 1 to 2
added a new file option called file info and on clicking the option a dialog with last opened will be shown

**Screenshots**
last-opened-re1 last-opened=re2

### CODE REVIEW

**Comment by Akash-Ramjyothi** [comment]
The Gradle doesn't build on testing it, I would recommend @cpg to reject this.

**Comment by chirag-jn** [comment]
@Akash-Ramjyothi can you post the error here?

**Comment by cpg** [comment]
@Akash-Ramjyothi will submit an improved PR for this feature.

**Comment by Akash-Ramjyothi** [comment]
I have done. It is PR #536.

**Comment by RGlass89** [comment]
I have tested this on my Samsung phone and I see two file for each file I open , the first one of the files is 0 k size

**Comment by cpg** [comment]
leaving it to #536

**Comment by chirag-jn** [comment]
Fixed in #574

**Pull request closed without merging**
