### PR TITLE
New language Hindi added with all issue resolved

### PR DESCRIPTION
**Pull request by Ayan-10**
@cpg Please have a look.

### CODE REVIEW

**Comment by chirag-jn** [comment]
@Ayan-10 have you tested this PR? Can you show me an output of the app's interface with Hindi language? In my opinion, it shouldn't work since you have created strings.xml under `values-hi-rIN` and not `values-hi`. Please check `LANGUAGES.md` for details.

**Review by chirag-jn — CHANGES_REQUESTED** [review]
Move strings.xml under values-h-rIN to values-hi folder.

**Comment by Ayan-10** [comment]
Screenshot_1604410709
Yes @chirag-jn , I tested the PR and here is the output screen with hindi language. It's working fine.

Still if you want me to put the file in values.hi. I can do that also.
But this also works fine.

Now tell me what should I do?

**Comment by chirag-jn** [comment]
@Ayan-10 in this case, you changed the system language. However, that wasn't the intended behavior. We were looking for some way to change the language in the app itself. If you go to the settings menu, you will see a language option. Does that toggle work for you?

**Review by chirag-jn — APPROVED** [review]

**Comment by Ayan-10** [comment]
Actually whenever I try to log in it shows connection error. So i can't log in but I did what you tell me to do

**Comment by chirag-jn** [comment]
> Actually whenever I try to log in it shows connection error. So i can't log in but I did what you tell me to do

Please follow the steps in README.md to understand the steps required for getting `api.properties` file.

**Comment by Ayan-10** [comment]
@chirag-jn honestly speaking I tried to understand the steps required for getting api.properties file but It is not happening. It shows this screen.
Screenshot_1604645610
I want to contribute to amahi. But for this issue I can't do that . So can you help me in that problem?

**Comment by cpg** [comment]
Hi @Ayan-10, sending an email without subject and a cryptic message, it's likely to become direct SPAM.

If you want to contribute to Amahi, we ask that you please read the docs and such carefully.

I have replied to your cryptic email.

Also, please note that are failing checks in this PR. We really really do not want to merge anything that may break the build.

**Comment by Ayan-10** [comment]
@cpg sorry I have not any intention to do spam and coming to PR when I requested the there was no conflicts in my PR I don't know how it happens but I will try my best to resolve this issue.

**Comment by Ayan-10** [comment]
@cpg checkout #699

**Comment by cpg** [comment]
CLosing this in favor of #699

**Pull request closed without merging**
