### PR TITLE
Add swipe to change songs

### PR DESCRIPTION
**Pull request by joydeepsaha05**
Implements #69

### CODE REVIEW

**Comment by csoni111** [comment]
@joydeepsaha05 the code looks clean and it's functioning properly. 
But I think it would be better if while swiping, the song art slides along with the swipe and next/previous song art becomes visible _(just as it happens in Google Play Music)_. This way it will give user a visual feedback that on swiping, the song can be changed!

**But a lot of changes would be required for doing this:**

- Instead of a single ImageView, a ViewPager would be required. (Here implementation from `ServerFileImageActivity` can be reused.)
- Instead of fetching metadata for single audio file, metadata would be fetched for all the files at once (or we can limit it to several files which are in the vicinity of the current file).
- If this is done then the code in this pr will become useless.

**How will it benefit?**

- No delay would be there in starting a song as the metadata would already have been fetched.
- We would be able to display the Song Artwork in the list of songs as their icons (just as it happens in the image previews).
- Changing to Next/Previous songs would be quick and without delay.
- And of course there will be visual feedback while swiping the songs.

**Comment by cpg** [comment]
If we were to implement this in two steps, would this be a first step, then add the rest of things @csoni111 suggested?

Or is it better/easier/faster to just do the (admittedly, quite nicer) suggestions all in one shot?

**Comment by joydeepsaha05** [comment]
@csoni111 I agree that having visual feedback while swiping would be much better, but there will be a lag since the songs are not stored locally. Having the songs stored in memory would leave a huge footprint. What do you think?

@cpg The code in this PR would be useless if we were to do the above changes.

**Comment by csoni111** [comment]
@joydeepsaha05 We do not have to store the songs locally, we just have to store the fetched metadata of those songs in Cache (Either memory based or disk based). This can be done by using one of the cache management libraries in android: [dualcache](https://github.com/vincentbrison/dualcache), [Reservoir](https://github.com/anupcowkur/Reservoir) etc. 
Also you can have a look at this music player's [source code](https://github.com/sdsmdg/MusicDNA/tree/master/app/src/main/java/com/sdsmdg/harjot/MusicDNA/imageLoader). This may be useful.

**Comment by joydeepsaha05** [comment]
@csoni111 I'll look into that. Closing this PR.

**Pull request closed without merging**
