### PR TITLE
Avoiding white-spaces in username

### LINKED ISSUE #511: No checks on username TextField if it contains spaces.
In Authentication class there's no condition that checks if username contains spaces before authentication.

### PR DESCRIPTION
**Pull request by mitrukahitesh**
1. White-space will not be accepted as first character in username.

**Before:**
before

**After:**
after

2. Leading and trailing white-spaces in username will be trimmed before going for authentication. Thus server need not check for the same.

Hope that it is useful.

### CODE REVIEW

**Comment by chirag-jn** [comment]
Fixes #525

**Comment by mitrukahitesh** [comment]
Commit "improvement in removing leading white-spaces from username" enables the following

gg

**Comment by chirag-jn** [comment]
In my opinion, that's over complicating a fairly simple task and we don't want our users to be frustrated on the login screen itself.

**Comment by mitrukahitesh** [comment]
In case a user copies username (with a space at the beginning, which is a common case) and pastes it in the app, will it pass the authentication? If no, then I have a reason to believe that it is useful.

**Comment by chirag-jn** [comment]
@mitrukahitesh the original intent of the PR is excellent where you are eliminating spaces at the beginning. I had concerns regarding the latest commit in this PR. How is it precisely helping?

**Comment by chirag-jn** [comment]
In fact, @mitrukahitesh, if you see this PR thread, you will see that I tagged an issue where I raised the exact same concern a long time back which you are trying to solve here.

**Comment by mitrukahitesh** [comment]
@chirag-jn If you observe carefully, you will notice that the initial commit alone is not sufficient to avoid space(s) at the beginning. For example: If I copy a username with a space at the beginning and paste, then the initial commit alone cannot remove the leading space. Similarly there might be other cases which the initial commit cannot handle alone. Whereas the latest commit takes care of the same. My intention with the latest commit was to assure that at any situation there is no leading space.

**Comment by mitrukahitesh** [comment]
However, if you believe it's not required, I will remove it.

**Comment by chirag-jn** [comment]
@mitrukahitesh It will be merged by tomorrow

**Comment by cpg** [comment]
Just **don't touch the UI please**. That can infuriate users. Just pass things through a cleanup function to remove spaces before and after (trim?).

**Pull request merged**
